// Client
export { ThreatClient } from './client';

// Resources
export {
  AddressesResource,
  ContractsResource,
  UrlResource,
  WalletsResource,
  LedgerResource,
  AccountTraceResource,
  UsageResource,
  TransactionsResource,
  ScanResource,
} from './resources';

// Types
export type {
  // Address types
  RiskIssue,
  FundFlowRisk,
  FundFlowData,
  AddressInfo,
  TokenRiskInfo,
  TaxInfo,
  AccessControlInfo,
  AddressDetails,
  DeployerRisk,
  AddressRiskResponse,
  SanctionedResponse,
  PoisoningResponse,
  AddressAnalysisOptions,
  SanctionsOptions,
  PoisoningOptions,
  QuickProfileChain,
  QuickProfileApproval,
  QuickProfileResponse,
  QuickProfileOptions,
  // Contract types
  ContractRiskResponse,
  SourceCodeAnalysis,
  Vulnerability,
  ContractSourceCodeResponse,
  TokenTaxResponse,
  SolidityAnalysisRequest,
  SolidityAnalysisResponse,
  ContractAnalysisOptions,
  SourceCodeOptions,
  TaxOptions,
  CodeAnalysisFinding,
  CodeAnalysisResponse,
  CodeAnalysisOptions,
  // URL types
  UrlRiskResponse,
  UrlAddResponse,
  UrlCheckOptions,
  // Wallet types
  TransactionIssue,
  TransactionDetails,
  WalletTransactionsResponse,
  TokenApproval,
  WalletApprovalsResponse,
  WalletTransactionsOptions,
  WalletApprovalsOptions,
  // Ledger types
  LedgerFamily,
  LedgerTransactionData,
  LedgerScanRequest,
  EIP712TypedData,
  LedgerEIP712Request,
  LedgerRisk,
  LedgerScanResponse,
  LedgerScanOptions,
  // Account trace types
  AccountTraceResponse,
  TraceConnection,
  TraceSummary,
  AccountTraceOptions,
  // Usage types
  UsageData,
  CurrentUsageResponse,
  UsagePlan,
  UsagePlansResponse,
  UsageOptions,
  MaxRpsOptions,
  // Transaction types
  TransactionChain,
  TransactionRiskResponse,
  TxRiskDetails,
  TrustFlag,
  TransactionOptions,
  // Scan types
  ScanChainId,
  ScanTransactionRequest,
  EIP712TypeDefinition,
  EIP712Domain,
  ScanEIP712TypedData,
  ScanEIP712Request,
  ScanRiskLevel,
  ScanWarning,
  AssetChange,
  ScanResponse,
  ScanEIP712Response,
  ScanOptions,
} from './types';

// Re-export commonly used types from core
export {
  Chain,
  ChainCompatibility,
  isEvmChain,
  CHAIN_NAMES,
  RiskModule,
  RiskScore,
  RiskLevel,
  TypeOfAddress,
  TokenStandard,
  WebacyError,
  AuthenticationError,
  RateLimitError,
  ValidationError,
  NotFoundError,
  NetworkError,
  type WebacyClientConfig,
  type RiskTag,
  type InformationalTag,
  type RiskCategory,
  type TokenMetadata,
} from '@webacy-xyz/sdk-core';
