// Client
export { ThreatClient } from './client';

// Resources
export {
  AddressesResource,
  ContractsResource,
  UrlResource,
  WalletsResource,
  LedgerResource,
  AccountTraceResource,
  UsageResource,
  TransactionsResource,
  ScanResource,
  BatchResource,
  RwaResource,
  VaultsResource,
} from './resources';

// Types
export type {
  // Address types
  RiskIssue,
  FundFlowRisk,
  FundFlowData,
  AddressInfo,
  TokenRiskInfo,
  TaxInfo,
  AccessControlInfo,
  AddressDetails,
  DeployerRisk,
  AddressRiskResponse,
  SanctionedResponse,
  PoisoningResponse,
  AddressAnalysisOptions,
  SanctionsOptions,
  PoisoningOptions,
  QuickProfileChain,
  QuickProfileApproval,
  QuickProfileResponse,
  QuickProfileOptions,
  AddressSummaryOptions,
  AddressSummaryResponse,
  // Contract types
  ContractRiskResponse,
  SourceCodeAnalysis,
  Vulnerability,
  ContractSourceCodeResponse,
  TokenTaxResponse,
  SolidityAnalysisRequest,
  SolidityAnalysisResponse,
  ContractAnalysisOptions,
  SourceCodeOptions,
  TaxOptions,
  CodeAnalysisFinding,
  CodeAnalysisResponse,
  CodeAnalysisOptions,
  AuditOptions,
  AuditResponse,
  SymbolLookupOptions,
  SymbolLookupResponse,
  // URL types
  UrlRiskResponse,
  UrlAddResponse,
  UrlCheckOptions,
  // Wallet types
  TransactionIssue,
  TransactionDetails,
  WalletTransactionsResponse,
  TokenApproval,
  WalletApprovalsResponse,
  WalletTransactionsOptions,
  WalletApprovalsOptions,
  // Ledger types
  LedgerFamily,
  LedgerTransactionData,
  LedgerScanRequest,
  EIP712TypedData,
  LedgerEIP712Request,
  LedgerRisk,
  LedgerScanResponse,
  LedgerScanOptions,
  // Account trace types
  AccountTraceResponse,
  TraceConnection,
  TraceSummary,
  AccountTraceOptions,
  // Usage types
  UsageData,
  CurrentUsageResponse,
  UsagePlan,
  UsagePlansResponse,
  UsageOptions,
  MaxRpsOptions,
  // Transaction types
  TransactionChain,
  TransactionRiskResponse,
  TxRiskDetails,
  TrustFlag,
  TransactionOptions,
  // Scan types
  ScanChainId,
  ScanTransactionRequest,
  EIP712TypeDefinition,
  EIP712Domain,
  ScanEIP712TypedData,
  ScanEIP712Request,
  ScanRiskLevel,
  ScanWarning,
  AssetChange,
  ScanResponse,
  ScanEIP712Response,
  ScanOptions,
  RiskScanOptions,
  RiskScanResponse,
  RiskScanStatusResponse,
  // Batch types
  BatchContractsRequest,
  BatchContractsResponse,
  BatchAddressesRequest,
  BatchAddressesResponse,
  BatchTransactionsRequest,
  BatchTransactionsResponse,
  BatchOptions,
  // RWA types
  RiskTier,
  DisplayTier,
  TokenType,
  LiquidityTier,
  RwaSortField,
  ScoreDriver,
  DenominationSummary,
  RwaTokenListItem,
  DepegSummary,
  RwaRiskSummary,
  RwaPagination,
  RwaAggregates,
  RwaTokenListResponse,
  RwaTokenIdentity,
  RwaDepegSnapshot,
  RwaHistoryPoint,
  RwaHistory,
  RwaDepegEvent,
  DepegEventEntry,
  RwaTokenDetailResponse,
  RwaListOptions,
  RwaDetailOptions,
  // Vault types
  VaultTier,
  VaultContractType,
  VaultProtocol,
  ListingVerdict,
  WithdrawalRisk,
  UnderlyingRiskTier,
  VaultSortKey,
  VaultContextItem,
  VaultListMetadata,
  VaultDetailMetadata,
  VaultRiskCategory,
  VaultRiskIssue,
  VaultRiskResponse,
  VaultTokenRisk,
  VaultLoopingMarket,
  VaultCompositionItem,
  VaultLstCollateralMarket,
  VaultMorphoData,
  VaultWebacyData,
  VaultListItem,
  VaultAggregateSummary,
  VaultAggregates,
  VaultPagination,
  VaultListResponse,
  VaultCursorListResponse,
  VaultDetailResponse,
  VaultListOptions,
  VaultCursorListOptions,
  VaultDetailOptions,
  VaultEvent,
  VaultEventsResponse,
  VaultEventsOptions,
  VaultEventsForAddressOptions,
  VaultHistoryRange,
  VaultTvlPoint,
  VaultTvlHistoryResponse,
  VaultTvlHistoryOptions,
} from './types';

// Enum re-exports (must be value exports, not type-only)
export { VaultEventCategory, VaultEventMechanism } from './types';

// Re-export commonly used types from core
export {
  Chain,
  ChainCompatibility,
  isEvmChain,
  CHAIN_NAMES,
  RiskModule,
  RiskScore,
  RiskLevel,
  TypeOfAddress,
  TokenStandard,
  WebacyError,
  AuthenticationError,
  RateLimitError,
  ValidationError,
  NotFoundError,
  NetworkError,
  type WebacyClientConfig,
  type RiskTag,
  type InformationalTag,
  type RiskCategory,
  type TokenMetadata,
} from '@webacy-xyz/sdk-core';
